### ISSUE TITLE
Add "test mode" functionality to send to a test email instead of the customer

### ISSUE THREAD

**Issue by brettflorio** [Foxy/foxy-node-subscription-alert#1]
In `config.ts`, let's add a something like:
```javascript
  // If `testing.enabled` is `true`, emails will _only_ be sent to the `testing.testEmail` address
  testing: {
    enabled: false,
    testEmail: "example@example.tld"
  }
```

If `config.testing.enabled === true`, all emails sent should use the `testEmail` address _instead of_ any other email address.

**Comment by ndvo** [comment]
I implemented test mode using https://ethereal.email/
Then I realized it should ask for a destination address instead.

Ethereal mail provides a sandbox mailbox where you can receive test email and the account is automatically created for you (credentials are displayed when the script is run).

@brettflorio Do you think this is enough or should we add the option for using a custom email address for testing?

https://github.com/Foxy/foxy-node-subscription-alert/tree/foxy/feature/test-mode#testing-your-emails
